repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix, --unsafe-fixes]
      - id: ruff-format

  - repo: https://github.com/crate-ci/committed
    rev: v1.1.11
    hooks:
      - id: committed
        stages: [commit-msg]
